apiVersion: batch/v1
kind: CronJob
metadata:
  name: aro-hcp-embedder-cronjob
  labels:
    app: aro-hcp-embedder
    type: scheduled
spec:
  schedule: "0 * * * *"  # Every hour at minute 0
  jobTemplate:
    metadata:
      labels:
        app: aro-hcp-embedder
        type: scheduled
    spec:
      template:
        metadata:
          labels:
            app: aro-hcp-embedder
            type: scheduled
        spec:
          restartPolicy: OnFailure
          containers:
          - name: aro-hcp-embedder
            image: quay.io/roivaz/aro-hcp-embedder:latest
            imagePullPolicy: IfNotPresent
            command: ["python", "embedding_generator.py"]
            envFrom:
            - configMapRef:
                name: postgresql-config
            - secretRef:
                name: config
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "2Gi"
                cpu: "1000m"
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                - ALL
          securityContext:
            fsGroup: 1000
      backoffLimit: 2
      activeDeadlineSeconds: 3600  # 1 hour timeout
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid  # Don't run concurrent jobs



