apiVersion: apps/v1
kind: Deployment
metadata:
  name: aro-hcp-mcp-server
  labels:
    app: aro-hcp-mcp-server
    component: mcp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aro-hcp-mcp-server
  template:
    metadata:
      labels:
        app: aro-hcp-mcp-server
        component: mcp-api
    spec:
      containers:
      - name: mcp-server
        # TODO: Replace with your container registry and image
        image: quay.io/roivaz/aro-hcp-embedder:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: PORT
          value: "8000"
        - name: HOST
          value: "0.0.0.0"
        envFrom:
        - configMapRef:
            name: postgresql-config
        - secretRef:
            name: config
        command:
        - python
        - mcp_server.py
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /home/embedder/.cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      restartPolicy: Always
