apiVersion: v1
kind: Service
metadata:
  name: aro-hcp-mcp-server
  labels:
    app: aro-hcp-mcp-server
    component: mcp-api
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http

  selector:
    app: aro-hcp-mcp-server

